server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


app:
  allow-all-get:
    - "/health"
    - "/users/available-usernames"
    - "/users/*/clucks"
    - "/clucks/**"
  allow-all-post:
    - "/users"

  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
